version: '3.3'
services:
  frontend:
    container_name: frontend
    image: nginx:1.19.9-alpine
    volumes:
      - ./dist:/var/project/dist
      - ./docker/nginx:/etc/nginx/conf.d
    restart: always

networks:
  default:
    external:
      name: sample